stages:
  preprocess:
    cmd: python src/preprocess.py
    deps:
      - scripts/preprocess.py
      - data/raw/creditcard-data.csv
    outs:
      - data/processed/train.csv
      #- data/processed/train.csv.dvc
      - data/processed/test.csv
      #- data/processed/test.csv.dvc
      - data/processed/val.csv
      #- data/processed/val.csv.dvc


  train:
    cmd: python src/train.py
    deps:
      - scripts/train.py
      - data/processed/train.csv
    outs:
      - models/model.pkl
    params:
      - train.random_state
      - train.test_size

  validate:
    cmd: python src/validate.py --model-version Staging --data-rev workspace
    deps:
      - scripts/validate.py
      - models/model.pkl
      - data/processed/test.csv
    outs:
      - models/validation/confusion_matrix.png
      - models/validation/roc_curve.png
