name: Run MLOps Pipeline on Data Change

on:
  push:
    paths:
      - '.github/workflows/**'
      - 'data/raw/**'
      - 'scripts/**'
      - 'dvc.yaml'
      - 'dvc.lock'
      - 'requirements.txt'
  workflow_dispatch:

jobs:
  pipeline:
    runs-on: ubuntu-latest
    env:
      MLFLOW_TRACKING_URI= ${{ secrets.MLFLOW_TRACKING_URI }}
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      MLFLOW_S3_ENDPOINT_URL: ${{ secrets.MLFLOW_S3_ENDPOINT_URL }}

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        pip install --upgrade pip
        pip install -r requirements.txt
        pip install 'dvc[s3]' awscli

    - name: Start MinIO server in Docker
      run: |
        docker run -d -p 9000:9000 --name minio \
          -e MINIO_ACCESS_KEY=$AWS_ACCESS_KEY_ID \
          -e MINIO_SECRET_KEY=$AWS_SECRET_ACCESS_KEY \
          minio/minio server /data
        # Wait for MinIO to be ready
        for i in {1..10}; do
          curl --silent --fail $MLFLOW_S3_ENDPOINT_URL/minio/health/live && break
          echo "Waiting for MinIO to start..."
          sleep 3
        done

    - name: Create mlflow bucket in MinIO
      run: |
        export AWS_ACCESS_KEY_ID=minio
        export AWS_SECRET_ACCESS_KEY=minio123
        aws --endpoint-url http://localhost:9000 s3 mb s3://mlflow || true

    - name: Configure DVC remote and pull
      run: |
        dvc remote modify minio endpointurl http://localhost:9000
        dvc remote modify minio access_key_id minio
        dvc remote modify minio secret_access_key minio123
    
    - name: Try pulling data, or fall back to repro + push
      run: |
        echo "Trying to pull data from DVC remote..."
        if ! dvc pull; then
          echo "⚠️ DVC pull failed — attempting to regenerate pipeline outputs..."
          dvc repro
          dvc push
        fi

    - name: Run pipeline
      run: |
        dvc repro

    - name: Push results
      run: |
        dvc push